---
- name: Configuring server for web hosting
  hosts: wpserver
  become: true

  vars_files:
   - wp_server/vars.yml

  handlers:
   - name: restart apache
     service: 
      name: apache2
      state: restarted
 

  tasks:

   - name: Ensure Apache, MySQL-cli and WordPress packets are installed.
     apt:
      name:
       - apache2
       - ghostscript
       - libapache2-mod-php
       - mysql-client
       - php
       - php-bcmath
       - php-curl
       - php-imagick
       - php-intl
       - php-json
       - php-mbstring
       - php-mysql
       - php-xml
       - php-zip
      update_cache: yes
      cache_valid_time: 3600
      state: present

   - name: Make sure Apache is running.
     service:
      name: apache2
      state: started

        #ovaj korak radis samo kada podignes dns server pre wp servera, jer inace slusa praznu IP adresu i ne moze da izadje na servere 8.8.8.8. itd
   - name: Change nameserver.
     copy:
      src: "{{ wordpress_server_location }}/{{ nameserver_files_folder }}/resolv.conf"
      dest: /etc/resolv.conf 
      remote_src: false

   - name: Create a www directory for WordPress installation.
     file:
      path: /srv/www
      owner: www-data
      state: directory

   - name: Download unzip command.
     apt:
      name: unzip
      state: present
      update_cache: yes 
      cache_valid_time: 3600

   - name: Download WordPress.
     get_url:
      url: "{{ wp_download_link }}"
      dest: /srv/www/latest.zip
    

   - name: Unzip downloaded latest.zip folder for site1.
     unarchive:
      src: /srv/www/latest.zip
      dest: "/srv/www"
      remote_src: true
      #creates??
      
   - name: Rename wordpress folders for site1.
     shell: " mv /srv/www/wordpress /srv/www/{{ item.value }}"
     args:
      creates: "/srv/www/{{ site_one_subdomain }}"
    
     with_items:
      - value: "{{ site_one_subdomain }}"

   - name: Unzip downloaded latest.zip folder for site2.
     unarchive:
      src: /srv/www/latest.zip
      dest: "/srv/www"
      remote_src: true

   - name: Rename wordpress folders for site2.
     shell: " mv /srv/www/wordpress /srv/www/{{ item.value }}"
     args: 
      creates: "/srv/www/{{ site_two_subdomain }}"
     with_items:
      - value: "{{ site_two_subdomain }}"


   - name: Disable 000-default.conf Apache default web page.
     file:
      path: "/etc/apache2/sites-enabled/000-default.conf"
      state: absent
     notify:
      - restart apache
      
   - name: Make WordPress configuration file.
     file:
      path: "/etc/apache2/sites-available/{{ item.value }}.conf"
      state: touch
     with_items:
      - value: "{{ site_one_subdomain }}"
      - value: "{{ site_two_subdomain }}"

   - name: Fill .conf files from sites-available with data.
     copy:
      src: "{{ wordpress_server_location }}/{{ item.value }}/{{ item.value }}.conf"
      dest: "/etc/apache2/sites-available/{{ item.value }}.conf" 
      remote_src: false
     with_items:
      - value: "{{ site_one_subdomain }}"
      - value: "{{ site_two_subdomain }}"

   - name: Make a symlinks for .conf files from sites-available to sites-enabled.
     file:
      src: "/etc/apache2/sites-available/{{ item.value }}.conf"
      dest: "/etc/apache2/sites-enabled/{{ item.value }}.conf"
      state: link  
     notify:
      - restart apache
     with_items:
      - value: "{{ site_one_subdomain }}"
      - value: "{{ site_two_subdomain }}"

   - name: Make wp-config.php files for site1.
     file:
      path: "/srv/www/{{ item.value }}/wp-config.conf"
      state: touch
     with_items:
      - value: "{{ site_one_subdomain }}"
  

   - name: Make wp-config.php files for site2.
     file:
      path: "/srv/www/{{ item.value }}/wp-config.conf"
      state: touch
     with_items:
      - value: "{{ site_two_subdomain }}"

   - name: Edit wp-config.php file for both sites.
     copy:
      src: "{{ wordpress_server_location }}/{{ item.value }}/wp-config.php"
      dest: "/srv/www/{{ item.value }}/wp-config.php"
     with_items:
      - value: "{{ site_one_subdomain }}"
      - value: "{{site_two_subdomain }}"
