---
 - name: Install bind9.
   hosts: dns
   become: true

   vars_files:
    - dns/vars.yml



   handlers:
    - name: restart bind9
      service:
       name: bind9
       state: restarted
   tasks:

    - name: Ensure bind9 is installed.
      apt:
       name: bind9
       update_cache: yes
       cache_valid_time: 3600
       state: present

    - name: Ensure bind9 is installed and running.
      service:
       name: bind9
       state: started
       enabled: yes

    - name: Copy bind configuration files.
      copy:
       src: "{{ item.src }}"
       dest: "{{ item.dest }}"
       owner: bind
       group: bind
       mode: 0644
       remote_src: false


      with_items:
       - src: "{{ dns_server_location }}/{{ bind_configuration_files_folder }}/named.conf.options"
         dest: "/etc/bind/named.conf.options"
       - src: "{{ dns_server_location }}/{{ bind_configuration_files_folder }}/named.conf.local"
         dest: "/etc/bind/named.conf.local"


    - name: Make files for forward and reverse zones.
      file:
       path: "{{item.value}}"
       state: touch


      with_items:
       - value: "/etc/bind/{{ second_level_domain }}.fwd"
       - value: "/etc/bind/{{ second_level_domain }}.rev"

    - name: Fill forward and reverse zone files with configuration.
      copy:
       src: "{{ item.src }}"
       dest: "{{ item.dest }}"
       owner: bind
       group: bind
       mode: 0644
       remote_src: false
      with_items:
       - src: "{{ dns_server_location }}/{{ zone_files_folder }}/{{ second_level_domain }}.fwd"
         dest: "/etc/bind/{{ second_level_domain }}.fwd"
       - src: "{{ dns_server_location }}/{{ zone_files_folder }}/{{ second_level_domain }}.rev"
         dest: "/etc/bind/{{ second_level_domain }}.rev"

    - name: Change nameserver.
      copy:
       src: "{{ dns_server_location }}/{{ nameserver_file_folder }}/resolv.conf"
       dest: /etc/resolv.conf
      notify:
       - restart bind9
