---
- name: Configuring master node.
  hosts: pxc_master_node
  become: true
    #ne sme da ide import_playbook, pa tasks, vec nastaju zbog toga roles !!! - import_playbok: ide na kraj posle tasks uvek !!!

  vars_files:
   - "master/vars.yml"
  roles:
   - pxc
   

  tasks:
   
   - name: Change nameserver.
     copy:
      src: "{{ location_dir }}/{{ master_dir }}/{{ nameserver_file_folder }}/resolv.conf"
      dest: /etc/resolv.conf 
  
   - name: Copy mysql configuration files.
     copy:
      src: "{{ location_dir }}/{{ master_dir }}/mysqld.cnf"
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf
      owner: mysql
      group: mysql
      mode: 0644
      remote_src: false
   
   - name: Fetch ca.pem, server_cert.pem and server_key.pem from master server.
     fetch:
      src: "/var/lib/mysql/{{ item.val }}"
      dest: "{{ location_dir }}/{{ master_dir }}/fetched"
     with_items:
      - val: "ca.pem"
      - val: "server-cert.pem"
      - val: "server-key.pem"

   - name: Mysql bootstrap.
     service:
      name: mysql@bootstrap.service
      state: started

   - name: Install keepalive service for providing virtual IP address of cluster on master server.
     apt:
      name: keepalived
      update_cache: true
      cache_valid_time: 3600
      state: present

   - name: Copy keepalive configuration files to master server.
     copy:
      src: "{{ location_dir }}/{{ master_dir }}/{{ keepalive_dir }}/keepalived.conf"
      dest: "/etc/keepalived/keepalived.conf"
      remote_src: false

   - name: Restart keepalive service
     service:
      name: keepalived.service
      state: restarted  



- import_playbook: slaveEnd.yml 






        #import playbook koji se odnosi na slave hosta !!! (kopiranje fetchovanih fajlova, restart servisa ) 
